CREATE TABLE parties
(
    party_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    number_of_party VARCHAR(255)                            NOT NULL,
    symbol          VARCHAR(255)                            NOT NULL,
    description     VARCHAR(255)                            NOT NULL,
    total_votes     INTEGER                                 NOT NULL,
    CONSTRAINT pk_parties PRIMARY KEY (party_id)
);

ALTER TABLE parties
    ADD CONSTRAINT uc_parties_name UNIQUE (name);

ALTER TABLE parties
    ADD CONSTRAINT uc_parties_numberofparty UNIQUE (number_of_party);