CREATE TABLE candidates
(
    candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    personal_no  VARCHAR(10)                             NOT NULL,
    party_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_candidates PRIMARY KEY (candidate_id)
);

ALTER TABLE candidates
    ADD CONSTRAINT uc_candidates_personal_no UNIQUE (personal_no);

ALTER TABLE candidates
    ADD CONSTRAINT FK_CANDIDATES_ON_PARTY FOREIGN KEY (party_id) REFERENCES parties (party_id);