CREATE TABLE suffrages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personal_no VARCHAR(255),
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    birth_date  date,
    nationality varchar(255),
    CONSTRAINT pk_suffrages PRIMARY KEY (id)
);