CREATE TABLE voting_dates
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    party_creation_deadline date,
    voting_day              date,
    CONSTRAINT pk_voting_dates PRIMARY KEY (id)
);