CREATE TABLE citizens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personal_no VARCHAR(255),
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    birth_date  date,
    nationality VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_citizens PRIMARY KEY (id)
);

