CREATE TABLE voters
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personal_no VARCHAR(255),
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    birth_date  date,
    CONSTRAINT pk_voters PRIMARY KEY (id)
);