CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    personal_no   VARCHAR(10)                             NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(50)                             NOT NULL,
    birth_date    date                                    NOT NULL,
    registered_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    has_voted     BOOLEAN                                 NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_personal_no UNIQUE (personal_no);